
services:
  web:
    build: .
    container_name: events_app
    env_file:
      - .env
    volumes:
      - ./lowen_derape:/app/lowen_derape

    restart: unless-stopped
    command: >
        uv run gunicorn lowen_derape.wsgi:application
        --bind 0.0.0.0:8000

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_lowen
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./lowen_derape/static:/app/lowen_derape/static
    depends_on:
      - web
    restart: unless-stopped